name: TownyResourcePack
description: Set a resource pack for your town so that everyone gets to see your beautiful constructions just like you!
author: Cocolennon
main: me.cocolennon.townyresourcepacks.Main
version: 1.0.0
api-version: 1.19
depend: [Towny]
permissions:
  townyresourcepacks.set:
    description: Allows a town's mayor to set its resource pack
  townyresourcepacks.clear:
    description: Allows a town's mayor to clear its resource pack